# Generated by Django 4.2.19 on 2025-02-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='email_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
