# Generated by Django 4.2.19 on 2025-02-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_email_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
