# Generated by Django 4.2.19 on 2025-02-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_cancelada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='motivo_consulta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo_terapia',
            field=models.CharField(max_length=50),
        ),
    ]
