# Generated by Django 4.2.19 on 2025-02-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='testimonios/'),
        ),
    ]
