# Generated by Django 4.2.19 on 2025-02-22 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('aprobado', models.BooleanField(default=False)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testimonio', to='reservas.reserva')),
            ],
        ),
    ]
