# Generated by Django 4.2.19 on 2025-03-26 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testimonios', '0002_testimonio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
