# Generated by Django 4.2.19 on 2025-04-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonios', '0003_testimonio_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='consentimiento',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha dado su consentimiento para publicar el testimonio.'),
        ),
    ]
