# Generated by Django 4.2.19 on 2025-02-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
                ('motivo_consulta', models.CharField(choices=[('Ansiedad y Depresión', 'Ansiedad Depresion'), ('Regulación emocional', 'Regulacion Emocional'), ('Autoestima y Conocimiento Personal', 'Autoestima'), ('Duelo y Cambios', 'Duelo Cambios'), ('Conflictos interpersonales', 'Conflictos Interpersonales'), ('Habilidades sociales', 'Habilidades Sociales'), ('Crianza', 'Crianza'), ('Productividad y gestión del tiempo', 'Productividad'), ('Crecimiento personal y hábitos saludables', 'Crecimiento Personal'), ('Fobias', 'Fobias'), ('Trastorno Obsesivo Compulsivo', 'Toc'), ('Trastornos del Neurodesarrollo', 'Neurodesarrollo'), ('Trastornos de la conducta alimentaria', 'Alimentacion')], max_length=50)),
                ('tipo_terapia', models.CharField(choices=[('Terapia Individual - 80€', 'Individual'), ('Terapia de Pareja - 105€', 'Pareja'), ('Pack 4 Sesiones - 300€', 'Pack Sesiones')], max_length=50)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('privacidad_aceptada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fecha_reserva', 'hora_reserva'],
                'unique_together': {('fecha_reserva', 'hora_reserva')},
            },
        ),
    ]
